/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT opencv_unitserver_evm3530_x64P.cdb */

/*  Include Header Files  */
#include <std.h>
#include <prd.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far PRD_Obj PWRM_slotFinalizer;
extern far SWI_Obj PRD_swi;
extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far LOG_Obj LOG_system;
extern far LOG_Obj ti_sdo_ce_osal_LOG_Buffer;
extern far LOG_Obj ti_sdo_ce_bioslog_create;
extern far LOG_Obj ti_sdo_ce_bioslog_synch;
extern far LOG_Obj ti_sdo_ce_bioslog_track;


#ifdef __cplusplus
}
#endif /* extern "C" */
