#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C64P{1,0,6.1,9
#
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/cvDFT_unitserver_evm3530/main.o64P.dep
endif

package/cfg/cvDFT_unitserver_evm3530/main.o64P: | .interfaces
package/cfg/cvDFT_unitserver_evm3530/main.o64P: main.c package/cfg/cvDFT_unitserver_evm3530_x64P.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl64P $< ...
	$(ti.targets.C64P.rootDir)/bin/cl6x -c  -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg/cvDFT_unitserver_evm3530 -fr=./package/cfg/cvDFT_unitserver_evm3530 -fc $<
	$(MKDEP) -a $@.dep -p package/cfg/cvDFT_unitserver_evm3530 -s o64P $< -C   -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg/cvDFT_unitserver_evm3530 -fr=./package/cfg/cvDFT_unitserver_evm3530
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/cvDFT_unitserver_evm3530/main.o64P:C_DIR=
package/cfg/cvDFT_unitserver_evm3530/main.o64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

package/cfg/cvDFT_unitserver_evm3530/main.s64P: | .interfaces
package/cfg/cvDFT_unitserver_evm3530/main.s64P: main.c package/cfg/cvDFT_unitserver_evm3530_x64P.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl64P -n $< ...
	$(ti.targets.C64P.rootDir)/bin/cl6x -c -n -s --symdebug:none -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg/cvDFT_unitserver_evm3530 -fr=./package/cfg/cvDFT_unitserver_evm3530 -fc $<
	$(MKDEP) -a $@.dep -p package/cfg/cvDFT_unitserver_evm3530 -s o64P $< -C  -n -s --symdebug:none -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg/cvDFT_unitserver_evm3530 -fr=./package/cfg/cvDFT_unitserver_evm3530
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/cvDFT_unitserver_evm3530/main.s64P:C_DIR=
package/cfg/cvDFT_unitserver_evm3530/main.s64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P.dep
endif

package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P: | .interfaces
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P: package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.s62 package/cfg/cvDFT_unitserver_evm3530_x64P.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) asm64P $< ...
	$(ti.targets.C64P.rootDir)/bin/cl6x -c -qq -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9   $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fr=./package/cfg -fa $<
	$(MKDEP) -a $@.dep -p package/cfg -s o64P $< -C  -qq -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9   $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P:C_DIR=
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/cvDFT_unitserver_evm3530_x64P.o64P.dep
endif

package/cfg/cvDFT_unitserver_evm3530_x64P.o64P: | .interfaces
package/cfg/cvDFT_unitserver_evm3530_x64P.o64P: package/cfg/cvDFT_unitserver_evm3530_x64P.c package/cfg/cvDFT_unitserver_evm3530_x64P.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl64P $< ...
	$(ti.targets.C64P.rootDir)/bin/cl6x -c  -qq -pdsw225 -mo --no_compress -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s o64P $< -C   -qq -pdsw225 -mo --no_compress -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/cvDFT_unitserver_evm3530_x64P.o64P:C_DIR=
package/cfg/cvDFT_unitserver_evm3530_x64P.o64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

package/cfg/cvDFT_unitserver_evm3530_x64P.s64P: | .interfaces
package/cfg/cvDFT_unitserver_evm3530_x64P.s64P: package/cfg/cvDFT_unitserver_evm3530_x64P.c package/cfg/cvDFT_unitserver_evm3530_x64P.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl64P -n $< ...
	$(ti.targets.C64P.rootDir)/bin/cl6x -c -n -s --symdebug:none -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s o64P $< -C  -n -s --symdebug:none -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/cvDFT_unitserver_evm3530_x64P.s64P:C_DIR=
package/cfg/cvDFT_unitserver_evm3530_x64P.s64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P.dep
endif

package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P: | .interfaces
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P: package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.c package/cfg/cvDFT_unitserver_evm3530_x64P.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl64P $< ...
	$(ti.targets.C64P.rootDir)/bin/cl6x -c  -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s o64P $< -C   -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P:C_DIR=
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.s64P: | .interfaces
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.s64P: package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.c package/cfg/cvDFT_unitserver_evm3530_x64P.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cl64P -n $< ...
	$(ti.targets.C64P.rootDir)/bin/cl6x -c -n -s --symdebug:none -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s o64P $< -C  -n -s --symdebug:none -qq -pdsw225 -mv64p -eo.o64P -ea.s64P   -Dxdc_cfg__header__='gsoc/algos/cvDFT_unitserver_evm3530/package/cfg/cvDFT_unitserver_evm3530_x64P.h'  -Dxdc_target_name__=C64P -Dxdc_target_types__=ti/targets/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_1_9 -O2  $(XDCINCS) -I$(ti.targets.C64P.rootDir)/include -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.s64P:C_DIR=
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.s64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P ::
	-$(RM) package/cfg/cvDFT_unitserver_evm3530/main.o64P
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.o64P
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P
	-$(RM) package/cfg/cvDFT_unitserver_evm3530/main.s64P
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.s64P
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.s64P

cvDFT_unitserver_evm3530.x64P: package/cfg/cvDFT_unitserver_evm3530/main.o64P package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P package/cfg/cvDFT_unitserver_evm3530_x64P.o64P package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P package/cfg/cvDFT_unitserver_evm3530_x64P.mak

clean::
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.mak
