/* this file was generated by linkcmd.xdt from the gnu.targets.arm
 * package
 */
INPUT(
    /usr/devel/a0272049/dvsdk_3_00_02_44/c6accel/soc/c6accelw/c6accelw_config/package/cfg/c6accelw_xv5T.ov5T
    /usr/devel/a0272049/dvsdk_3_00_02_44/xdctools_3_15_01_59/packages/gnu/targets/arm/rtsv5T/lib/gnu.targets.arm.rtsv5T.av5T
)

