#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = gsoc/algos/cvDFT_unitserver_evm3530
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCPKGS = $(call pkgsearch,ti/bios/include )
XDCINCS += $(if $(XDCPKGS),-I$(subst $(space), -I,$(XDCPKGS)))
IMPORTPATH += $(if $(XDCPKGS),;$(subst $(space),;,$(XDCPKGS)))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/template.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/template.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_code.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_code.xs
/media/disk/OE/work/ti/my_fir_test/config.bld:
package.mak: /media/disk/OE/work/ti/my_fir_test/config.bld
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/om2.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/om2.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs
package.mak: package.bld
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/IPackage.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/IPackage.xs
/media/disk/OE/work/ti/ti-xdctools-tree/include/utils.tci:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/include/utils.tci
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/package.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/package.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_data.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_data.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xdc.tci:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xdc.tci
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/ITarget.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/ITarget.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/package.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/package.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/package.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/package.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs
endif

ti.targets.C64P.rootDir ?= /media/disk/OE/work/ti/ti-cgt6x-tree
ti.targets.packageBase ?= /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o64P
.PHONY: all,64P .dlls,64P .executables,64P test,64P
all,64P: .executables,64P
.executables,64P: .libraries,64P
.executables,64P: .dlls,64P
.dlls,64P: .libraries,64P
.libraries,64P: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,64P
	@$(ECHO) xdc .executables,64P
	@$(ECHO) xdc .libraries,64P
	@$(ECHO) xdc .dlls,64P


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_gsoc.algos.cvDFT_unitserver_evm3530.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package gsoc.algos.cvDFT_unitserver_evm3530" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,64P .executables: cvDFT_unitserver_evm3530.x64P

package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.c package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.s62 package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.cmd: override _PROG_NAME := cvDFT_unitserver_evm3530.x64P
package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.c package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.s62 package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.cmd: override _PROG_XSOPTS =  -Dxdc.cfg.check.fatal=false
-include package/cfg/cvDFT_unitserver_evm3530_x64P.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/cvDFT_unitserver_evm3530_x64P.dep
endif
package/cfg/cvDFT_unitserver_evm3530/main.o64P package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P package/cfg/cvDFT_unitserver_evm3530_x64P.o64P package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P : | package/cfg/cvDFT_unitserver_evm3530_x64P.xdl
cvDFT_unitserver_evm3530.x64P: package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.cmd
cvDFT_unitserver_evm3530.x64P:
	$(RM) $@
	@$(MSG) lnk64P $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.C64P.rootDir)/bin/lnk6x -w -q -u _c_int00 -l link.cmd -q -o $@ package/cfg/cvDFT_unitserver_evm3530/main.o64P package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P package/cfg/cvDFT_unitserver_evm3530_x64P.o64P package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P  package/cfg/cvDFT_unitserver_evm3530_x64P.xdl  -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.C64P.rootDir)/lib/rts64plus.lib
	
cvDFT_unitserver_evm3530.x64P:C_DIR=
cvDFT_unitserver_evm3530.x64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)


ifeq (,$(wildcard .libraries,64P))
cvDFT_unitserver_evm3530.x64P package/cfg/cvDFT_unitserver_evm3530_x64P.c: .libraries,64P
endif

package/cfg/cvDFT_unitserver_evm3530_x64P.c package/cfg/cvDFT_unitserver_evm3530_x64P.h package/cfg/cvDFT_unitserver_evm3530_x64P.xdl: override _PROG_NAME := cvDFT_unitserver_evm3530.x64P
package/cfg/cvDFT_unitserver_evm3530_x64P.c package/cfg/cvDFT_unitserver_evm3530_x64P.xdl: override _PROG_XSOPTS =  -Dxdc.cfg.check.fatal=false
package/cfg/cvDFT_unitserver_evm3530_x64P.c: package/cfg/cvDFT_unitserver_evm3530_x64P.cfg
cvDFT_unitserver_evm3530.test test,64P test: cvDFT_unitserver_evm3530.x64P.test

cvDFT_unitserver_evm3530.x64P.test:: cvDFT_unitserver_evm3530.x64P
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 cvDFT_unitserver_evm3530.x64P.test
else
	@$(MSG) running $<  ...
	$(call EXEC.cvDFT_unitserver_evm3530.x64P, ) 
endif


clean:: clean,64P
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.cfg
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.dep
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.c
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.xdc.inc

clean,64P::
	-$(RM) cvDFT_unitserver_evm3530.x64P
	-$(RM) .tmp,cvDFT_unitserver_evm3530.x64P,*

clean:: 
	-$(RM) package/cfg/cvDFT_unitserver_evm3530_x64P.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
cvDFT_unitserver_evm3530_x64Pcfg_c.o64P,copy : package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.o64P
cvDFT_unitserver_evm3530_x64Pcfg_c.s64P,copy : package/cfg/cvDFT_unitserver_evm3530_x64Pcfg_c.s64P
cvDFT_unitserver_evm3530_x64Pcfg.o64P,copy : package/cfg/cvDFT_unitserver_evm3530_x64Pcfg.o64P
cvDFT_unitserver_evm3530_x64P.o64P,copy : package/cfg/cvDFT_unitserver_evm3530_x64P.o64P
cvDFT_unitserver_evm3530_x64P.s64P,copy : package/cfg/cvDFT_unitserver_evm3530_x64P.s64P
main.o64P,copy : package/cfg/cvDFT_unitserver_evm3530/main.o64P
main.s64P,copy : package/cfg/cvDFT_unitserver_evm3530/main.s64P

$(XDCCFGDIR)%cfg.s62 $(XDCCFGDIR)%cfg_c.c $(XDCCFGDIR)%cfg.cmd $(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,gsoc_algos_cvDFT_unitserver_evm3530
gsoc_algos_cvDFT_unitserver_evm3530.tar: package/build.cfg
gsoc_algos_cvDFT_unitserver_evm3530.tar: package/info
gsoc_algos_cvDFT_unitserver_evm3530.tar: package/package.ext.xml
gsoc_algos_cvDFT_unitserver_evm3530.tar: package/package.xdc.inc
gsoc_algos_cvDFT_unitserver_evm3530.tar: cvDFT_unitserver_evm3530.x64P
gsoc_algos_cvDFT_unitserver_evm3530.tar: package/package.bld.xml
gsoc_algos_cvDFT_unitserver_evm3530.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/gsoc_algos_cvDFT_unitserver_evm3530.tar.dep
endif
package/rel/gsoc_algos_cvDFT_unitserver_evm3530/gsoc/algos/cvDFT_unitserver_evm3530/package/package.rel.xml:

gsoc_algos_cvDFT_unitserver_evm3530.tar: package/rel/gsoc_algos_cvDFT_unitserver_evm3530.xdc.inc package/rel/gsoc_algos_cvDFT_unitserver_evm3530/gsoc/algos/cvDFT_unitserver_evm3530/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/gsoc_algos_cvDFT_unitserver_evm3530.xdc.inc,package/rel/gsoc_algos_cvDFT_unitserver_evm3530.tar.dep)


release release,gsoc_algos_cvDFT_unitserver_evm3530: all gsoc_algos_cvDFT_unitserver_evm3530.tar
clean:: .clean
	-$(RM) gsoc_algos_cvDFT_unitserver_evm3530.tar
	-$(RM) package/rel/gsoc_algos_cvDFT_unitserver_evm3530.xdc.inc
	-$(RM) package/rel/gsoc_algos_cvDFT_unitserver_evm3530.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg/cvDFT_unitserver_evm3530))
    $(shell $(MKDIR) package/cfg/cvDFT_unitserver_evm3530)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/gsoc.algos.cvDFT_unitserver_evm3530.pjt
