#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = gsoc/algos/cvDFT
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs
package.mak: package.bld
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/template.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/template.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_code.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_code.xs
/media/disk/OE/work/ti/my_fir_test/config.bld:
package.mak: /media/disk/OE/work/ti/my_fir_test/config.bld
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/om2.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/om2.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/IPackage.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/IPackage.xs
/media/disk/OE/work/ti/ti-xdctools-tree/include/utils.tci:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/include/utils.tci
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/package.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/package.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_data.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/MSP430_large_data.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xdc.tci:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xdc.tci
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/ITarget.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/ti/targets/ITarget.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/package.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/package.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/package.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/package.xs
/media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs:
package.mak: /media/disk/OE/work/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs
endif

all,64P .libraries,64P .dlls,64P .executables,64P test,64P:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_gsoc.algos.cvDFT.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package gsoc.algos.cvDFT" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js gsoc.algos.cvDFT $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,gsoc_algos_cvDFT
gsoc_algos_cvDFT.tar: package/build.cfg
gsoc_algos_cvDFT.tar: package/package.cfg.xdc.inc
gsoc_algos_cvDFT.tar: package/package.ext.xml
gsoc_algos_cvDFT.tar: package/package.xdc.inc
gsoc_algos_cvDFT.tar: package/package.bld.xml
gsoc_algos_cvDFT.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/gsoc_algos_cvDFT.tar.dep
endif
package/rel/gsoc_algos_cvDFT/gsoc/algos/cvDFT/package/package.rel.xml:

gsoc_algos_cvDFT.tar: package/rel/gsoc_algos_cvDFT.xdc.inc package/rel/gsoc_algos_cvDFT/gsoc/algos/cvDFT/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/gsoc_algos_cvDFT.xdc.inc,package/rel/gsoc_algos_cvDFT.tar.dep)


release release,gsoc_algos_cvDFT: all gsoc_algos_cvDFT.tar
clean:: .clean
	-$(RM) gsoc_algos_cvDFT.tar
	-$(RM) package/rel/gsoc_algos_cvDFT.xdc.inc
	-$(RM) package/rel/gsoc_algos_cvDFT.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


