/* this file was generated by linkcmd.xdt from the gnu.targets.arm
 * package
 */
INPUT(
    /media/disk/OE/dspacceleration/opencv-dsp-acceleration/dsp_opencv/opencv_iuniversal/gsoc/apps/cvDFT/cfg/linux/remote_ti_platforms_evm3530/package/cfg/remote_ti_platforms_evm3530_xv5T.ov5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/universal/lib/release/universal.av5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/lib/release/ce.av5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/alg/lib/release/Algorithm_noOS.av5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/alg/lib/release/alg.av5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/ipc/dsplink/lib/release/ipc_dsplink_3530.av5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/osal/linux/lib/release/osal_linux_470.av5T
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/acpy3/lib/release/acpy3.a470MV
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/dman3/lib/release/dman3Cfg.a470MV
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/rmm.a470MV
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/smgr.a470MV
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/rmmp.a470MV
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/smgrmp.a470MV
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/shm.a470MV
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/fc/memutils/lib/release/memutils.av5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/utils/xdm/lib/release/XdmUtils.av5T
    /media/disk/OE/work/ti/ti-codec-engine-tree/packages/ti/sdo/ce/node/lib/release/node.av5T
    /media/disk/OE/work/ti/ti-framework-components-tree/packages/ti/sdo/utils/trace/lib/release/gt.av5T
    /media/disk/OE/work/ti/ti-local-power-manager-tree/packages/ti/bios/power/lib/release/lpm_linux.av5T
    /media/disk/OE/work/ti/ti-linuxutils-tree/packages/ti/sdo/linuxutils/cmem/lib/cmem.a470MV
    /media/disk/OE/work/ti/ti-dsplink-tree/packages/dsplink/gpp/export/BIN/Linux/OMAP3530/RELEASE/dsplink.lib
    /media/disk/OE/work/ti/ti-xdctools-tree/packages/gnu/targets/arm/rtsv5T/lib/gnu.targets.arm.rtsv5T.av5T
)

SECTIONS {
    xdc.meta (COPY) : {*(xdc.meta)} 

}

